### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "Admin123"
}


### Create a user
POST http://192.168.1.4:3000/register
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}


### getAll journals
GET http://192.168.1.4:3000/journals
Content-Type: application/json

